## Homework_6

In [1]:
import numpy as np

In [2]:
from math import sqrt

1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [3]:
# ковариация

In [4]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])

In [5]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [6]:
covar = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
covar

9157.839999999997

In [7]:
np.cov(zp,ks,ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [8]:
round(covar,2) == round(np.cov(zp,ks,ddof=0)[0,1],2)

True

In [9]:
# коэффициент корреляции Пирсона

In [10]:
sigma_X = sqrt(sum((x - np.mean(zp))**2 for x in zp) / (len(zp)))
sigma_X

59.115480206118605

In [11]:
sigma_Y = sqrt(sum((x - np.mean(ks))**2 for x in ks) / (len(ks)))
sigma_Y

174.55340157098058

In [12]:
r_XY = covar / (sigma_X * sigma_Y)
r_XY

0.8874900920739158

In [13]:
R_XY = np.cov(zp,ks,ddof=1) / (np.std(zp,ddof=1)*np.std(ks,ddof=1))
R_XY

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [14]:
np.corrcoef(zp,ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [15]:
round(r_XY,8) == round(R_XY[0,1],8) == round(np.corrcoef(zp,ks)[0,1],8)

True

2.	Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [16]:
IQ = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

In [17]:
mean_IQ = sum(IQ)/len(IQ)
mean_IQ

118.1

In [18]:
len(IQ)

10

In [19]:
sigma_IQ = sqrt(sum((x - mean_IQ)**2 for x in IQ) / (len(IQ) - 1))
sigma_IQ

10.54566788359614

In [20]:
t_005_9 = 2.262

In [21]:
left_interval = mean_IQ - t_005_9 * sigma_IQ / sqrt(len(IQ))
left_interval

110.55660776308164

In [22]:
right_interval = mean_IQ + t_005_9 * sigma_IQ / sqrt(len(IQ))
right_interval

125.64339223691834

In [23]:
print(f'Доверительный интервал: ["{left_interval}";"{right_interval}"]')

Доверительный интервал: ["110.55660776308164";"125.64339223691834"]


3.	Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [24]:
D = 25

In [25]:
n = 27

In [26]:
M = 174.2

In [27]:
alpha = 1 - 0.95

In [28]:
Z_half_alpha = 1.96

In [29]:
left_interval = M - Z_half_alpha * sqrt(D) / sqrt(n)
left_interval

172.31398912064722

In [30]:
right_interval = M + Z_half_alpha * sqrt(D) / sqrt(n)
right_interval

176.08601087935276

In [31]:
print(f'Доверительный интервал: ["{left_interval}";"{right_interval}"]')

Доверительный интервал: ["172.31398912064722";"176.08601087935276"]
